[package]
name = "hoard"
version = "0.0.1"
edition = "2018"
readme = "README.md"
license = "MIT"

[dependencies]
# Command lien argument parser
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
# pretty dialogues in terminal
dialoguer = "0.8.0"
# Cross terminal support
crossterm = "0.20.0"
# Yaml support to save/load command pallettes
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
anyhow = "1.0.38"
dirs = "3.0.1"
log = "0.4"
simple_logger = "1.11.0"
prettytable-rs = "0.8.0"
tui = { version = "0.14.0", features = ["crossterm"]}
tokio = { version = "0.2", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
rand = { version = "0.7.3", default-features = false, features = ["std"] }
thiserror = "1.0"
