[package]
name = "hoard"
version = "0.2.0-beta"
edition = "2018"
readme = "README.md"
license = "MIT"

[dependencies]
# Command lien argument parser
clap = { version = "2.33.3", features = ["yaml"] }
# pretty dialogues in terminal
dialoguer = "0.8.0"
termion = "1.5.6"
# Yaml support to save/load command pallettes
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
anyhow = "1.0.38"
dirs = "3.0.1"
log = "0.4"
eyre = "0.6"
simple_logger = "1.11.0"
prettytable-rs = "0.8.0"
tui = { version = "0.16.0", features = ["termion"]}
chrono = { version = "0.4", features = ["serde"] }
rand = { version = "0.8.4", default-features = false, features = ["std"] }
thiserror = "1.0"
tokio = { version = "1.11.0", features = ["full"] }
