[package]
name = "hoard-rs"
version = "1.0.0"
edition = "2018"
readme = "README.md"
license = "MIT"
authors = ["Denis Heid"]
description = "hoard - cli command organizer written in Rust"
homepage = "https://github.com/Hyde46/hoard"
repository = "https://github.com/Hyde46/hoard"

[package.metadata.deb]
maintainer = "Denis Heid"
copyright = "2021, Denis Heid"
license-file = ["LICENSE"]
depends = "$auto"
section = "utility"

[package.metadata.rpm]
package = "hoard"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[[bin]]
name = "hoard"
path = "src/main.rs"

[dependencies]
# Command lien argument parser
clap = { version = "3.0.12", features = ["yaml"] }
# pretty dialogues in terminal
dialoguer = "0.9.0"
termion = "1.5.6"
# Yaml support to save/load command pallettes
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
anyhow = "1.0.38"
dirs = "4.0.0"
log = "0.4"
eyre = "0.6"
simple_logger = "1.11.0"
prettytable-rs = "0.8.0"
tui = { version = "0.17.0", features = ["termion"]}
chrono = { version = "0.4", features = ["serde"] }
rand = { version = "0.8.4", default-features = false, features = ["std"] }
thiserror = "1.0"
crossbeam-channel = "0.5.1"
tokio = { version = "1.11.0", features = ["full"] }
array_tool = "1.0.3"
reqwest = {version="0.11.4"}
url = {version="2.2.2"}
console = "0.15.0"
